### ISSUE TITLE
Invalid CloudEvent payload

### ISSUE THREAD

**Issue by matzew** [smallrye/smallrye-reactive-messaging#71]
Using 0.0.5-SNAPSHOT... and when creating - and sending a Cloudevent, like:

```
    final CloudEventMessage<String> kafkaMessageCloudEventMessage = new CloudEventMessageBuilder()
    .id(UUID.randomUUID().toString())
    .source(URI.create(message.getTopic()))
    .type("kafka-event")
    .data(message.getPayload())
    .build();

    return HttpMessage.HttpMessageBuilder.<CloudEventMessage<String>>create()
      .withMethod("POST")
      .withPayload(kafkaMessageCloudEventMessage)
      .withHeader("Content-Type", "application/cloudevents+json")
      .build();

```

the entire object to the wire/http server is:

```
{"payload":"{\"signal\":2,\"data\":{\"brokerage\":{\"broker\":{\"id\":\"BMS-USB-G-JACE\",\"meta\":{\"protocol\":\"BACNET\",\"building\":\"Urban Sciences Building\",\"buildingFloor\":\"G\"}},\"id\":\"Drivers.GF_Event_Space_Electricity_Meters.GF_ES_Mechcanical_Plant.points.GF_ES_CHW_Pump_Current\",\"meta\":{}},\"entity\":{\"name\":\"Urban Sciences Building: Floor G\",\"meta\":{\"building\":\"Urban Sciences Building\",\"buildingFloor\":\"G\"}},\"feed\":{\"metric\":\"GF ES CHW Pump Current\",\"meta\":{}},\"timeseries\":{\"unit\":\"no units\",\"value\":{\"time\":\"2019-03-19T10:05:23.196Z\",\"timeAccuracy\":4.953,\"data\":0.15316040813922882,\"type\":\"Real\"}}},\"recipients\":0}","schemaURL":null,"contentType":null,"specVersion":"0.2","data":"{\"signal\":2,\"data\":{\"brokerage\":{\"broker\":{\"id\":\"BMS-USB-G-JACE\",\"meta\":{\"protocol\":\"BACNET\",\"building\":\"Urban Sciences Building\",\"buildingFloor\":\"G\"}},\"id\":\"Drivers.GF_Event_Space_Electricity_Meters.GF_ES_Mechcanical_Plant.points.GF_ES_CHW_Pump_Current\",\"meta\":{}},\"entity\":{\"name\":\"Urban Sciences Building: Floor G\",\"meta\":{\"building\":\"Urban Sciences Building\",\"buildingFloor\":\"G\"}},\"feed\":{\"metric\":\"GF ES CHW Pump Current\",\"meta\":{}},\"timeseries\":{\"unit\":\"no units\",\"value\":{\"time\":\"2019-03-19T10:05:23.196Z\",\"timeAccuracy\":4.953,\"data\":0.15316040813922882,\"type\":\"Real\"}}},\"recipients\":0}","time":null,"id":"2f9f3459-7446-42c3-a716-991dfe6d8dc5","type":"kafka-event","extensions":[],"source":"my-topic"}
```

this includes a `payload` field, which is not compliant to the CloudEvents spec - it should be _only_ data

**Comment by cescoffier** [comment]
@matzew can you confirm it's fixed now?

**Comment by ricardozanini** [comment]
I believe we still have this problem. Having this:

```java
        final CloudEventMessage<String> ce = new CloudEventMessageBuilder<String>()
                .withId(UUID.randomUUID().toString())
                .withType("mytype")
                .withData(message.getData().orElse(""))
                .withDataContentType("text/plain")
                .withSource(new URI("/smallrye/cloudEventMessage"))
                .build();

        return  HttpMessage.HttpMessageBuilder.<CloudEventMessage<String>>create()
                .withMethod("POST")
                .withPayload(ce)
                .withHeader("Content-Type", "application/cloudevents+json")
                .build();
```

The generated JSON is:

```json
{
   "attributes":{
      "id":"1a4c4c45-524e-4dab-a45d-1284a7e36c71",
      "source":"/smallrye/cloudEventMessage",
      "specversion":"1.0",
      "type":"mytype",
      "datacontenttype":"text/plain"
   },
   "extensions":{
      "data":"0"
   },
   "payload":"0",
   "data":"0",
   "ack":{

   },
   "nack":{

   },
   "metadata":[

   ]
}
```

Which is not complaint with the spec. Attributes should be unwrapped:

```json
{
    "specversion" : "1.0",
    "type" : "com.github.pull.create",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

This is happening because [`DefaultCloudEventMessage`](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-cloud-events/src/main/java/io/smallrye/reactive/messaging/cloudevents/DefaultCloudEventMessage.java) is wrapping the original `CloudEventImpl` Jackson annotations (from SDK version 1.1.0).

What I'm doing is the right way of returning CloudEvents in a processor? Since @matzew closed this issue, I assume is something on my side.

**Comment by cescoffier** [comment]
The SDK we use is very outdated. Unfortunately, all the updates contain breaking changes.

**Comment by ricardozanini** [comment]
Do you think it's feasible to use 2.0.0-milestone1? I can send a PR fixing this issue and updating the SDK. :)
